# Document:
# http://simiki.org/docs/configuration.html

url: 
title: personal knowledge wiki
keywords: technology
description: A wiki website of daysneco
author: daysneco

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple2