# Document:
# http://simiki.org/docs/configuration.html

url: 
title: Norris
keywords: technology
description: A wiki website of Norris
author: Norris

root: /wiki

deploy:
    - type: git
      remote: origin
      branch: gh-pages
      
theme: simple
#theme: yasimple_x2
